feat: RoF (#325)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,20 +23,20 @@ commands:
         type: string
       ruby:
         type: string
-      rspec:
+      rspec-rails:
         type: string
         default: "latest"
     steps:
       - run:
           working_directory: << parameters.path >>
           command: |
-            if [[ "<< parameters.rspec >>" != "latest" ]]; then
-              sed -i 's/.*gem.*rspec-core.*/gem "rspec-core", "<< parameters.rspec >>"/g' ./Gemfile
-              echo "Updated RSpec version in Gemfile"
+            if [[ "<< parameters.rspec-rails >>" != "latest" ]]; then
+              sed -i 's/.*gem.*rspec-rails.$/gem "rspec-rails", "<< parameters.rspec-rails >>"/g' ./Gemfile
+              echo "Updated rspec-rails version in Gemfile"
             fi
       - restore_cache:
           keys:
-            - v1-bundler-rails-{{ checksum "Gemfile.lock" }}-ruby-<< parameters.ruby >>-rspec-<< parameters.rspec >>
+            - v1-bundler-rails-{{ checksum "Gemfile.lock" }}-ruby-<< parameters.ruby >>-rspec-rails-<< parameters.rspec-rails >>
             - v1-bundler-rails-{{ checksum "Gemfile.lock" }}-ruby-<< parameters.ruby >>-
             - v1-bundler-rails-{{ checksum "Gemfile.lock" }}-
             - v1-bundler-rails-
@@ -48,7 +48,7 @@ commands:
       - save_cache:
           paths:
             - << parameters.path >>/vendor/bundle
-          key: v1-bundler-rails-{{ checksum "Gemfile.lock" }}-ruby-<< parameters.ruby >>-rspec-<< parameters.rspec >>
+          key: v1-bundler-rails-{{ checksum "Gemfile.lock" }}-ruby-<< parameters.ruby >>-rspec-rails-<< parameters.rspec-rails >>
 
 jobs:
   unit:
@@ -81,7 +81,7 @@ jobs:
       - run:
           command: |
             if [[ "<< parameters.rspec >>" != "latest" ]]; then
-              sed -i 's/.*gem.*rspec-core.*/gem "rspec-core", "<< parameters.rspec >>"/g' ./Gemfile
+              sed -i 's/.*gem.*rspec.$/gem "rspec", "<< parameters.rspec >>"/g' ./Gemfile
               echo "Updated RSpec version in Gemfile"
             fi
       - restore_cache:
@@ -102,8 +102,8 @@ jobs:
           command: |
             ruby --version
             bundle exec rspec --version
-            RSPEC=$(bundle exec rspec --version | grep rspec-core | head -n1 | cut -d " " -f5)
-            [ "<< parameters.rspec >>" != "latest" ] && [ $RSPEC != << parameters.rspec >> ] && exit 1 || echo "Correct version of RSpec installed: << parameters.rspec >>"
+            RSPEC=$(bundle exec rspec --version | grep -i rspec | head -n1 | cut -d " " -f2)
+            [ "<< parameters.rspec >>" != "latest" ] && [ "$RSPEC" != "<< parameters.rspec >>" ] && exit 1 || echo "Correct version of RSpec installed: << parameters.rspec >>"
       - run: bundle exec rspec spec/integration/runners/queue/rspec_runner_spec.rb
 
   e2e-regular-rspec:
@@ -113,7 +113,7 @@ jobs:
     parameters:
       ruby:
         type: string
-      rspec:
+      rspec-rails:
         type: string
     docker:
       - image: cimg/ruby:<< parameters.ruby >>-browsers
@@ -135,15 +135,15 @@ jobs:
       - setup_rails_app_with_knapsack_pro:
           path: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           ruby: << parameters.ruby >>
-          rspec: << parameters.rspec >>
+          rspec-rails: << parameters.rspec-rails >>
       - run: dockerize -wait tcp://localhost:5432 -timeout 1m
       - run:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: |
             ruby --version
             bundle exec rspec --version
-            RSPEC=$(bundle exec rspec --version | grep rspec-core | head -n1 | cut -d " " -f5)
-            [ "<< parameters.rspec >>" != "latest" ] && [ $RSPEC != << parameters.rspec >> ] && exit 1 || echo "Correct version of RSpec installed: << parameters.rspec >>"
+            VERSION=$(bundle exec rspec --version | grep -i rspec-rails | head -n1 | cut -d " " -f5)
+            [ "<< parameters.rspec-rails >>" != "latest" ] && [ "$VERSION" != "<< parameters.rspec-rails >>" ] && exit 1 || echo "Correct version of rspec-rails installed: << parameters.rspec-rails >>"
       - run:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: bin/rails db:setup
@@ -199,7 +199,7 @@ jobs:
     parameters:
       ruby:
         type: string
-      rspec:
+      rspec-rails:
         type: string
     parallelism: 2
     working_directory: ~/knapsack_pro-ruby
@@ -213,6 +213,7 @@ jobs:
           RACK_ENV: test
           KNAPSACK_PRO_ENDPOINT: https://api-staging.knapsackpro.com
           KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: $KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC
+          KNAPSACK_PRO_LOG_LEVEL: debug
           EXTRA_TEST_FILES_DELAY: 10
       - image: cimg/postgres:14.7
         environment:
@@ -224,41 +225,37 @@ jobs:
       - setup_rails_app_with_knapsack_pro:
           path: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           ruby: << parameters.ruby >>
-          rspec: << parameters.rspec >>
+          rspec-rails: << parameters.rspec-rails >>
       - run: dockerize -wait tcp://localhost:5432 -timeout 1m
       - run:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: |
             ruby --version
             bundle exec rspec --version
-            RSPEC=$(bundle exec rspec --version | grep rspec-core | head -n1 | cut -d " " -f5)
-            [ "<< parameters.rspec >>" != "latest" ] && [ $RSPEC != << parameters.rspec >> ] && exit 1 || echo "Correct version of RSpec installed: << parameters.rspec >>"
+            VERSION=$(bundle exec rspec --version | grep -i rspec-rails | head -n1 | cut -d " " -f5)
+            [ "<< parameters.rspec-rails >>" != "latest" ] && [ "$VERSION" != "<< parameters.rspec-rails >>" ] && exit 1 || echo "Correct version of rspec-rails installed: << parameters.rspec-rails >>"
       - run:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: bin/rails db:setup
       - run:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: |
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue"
+            export KNAPSACK_PRO_TEST_QUEUE_ID="<< pipeline.number >>:$CIRCLE_JOB--queue"
+            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--<< pipeline.number >>:$CIRCLE_JOB--queue"
             bundle exec rake knapsack_pro:queue:rspec
       - run:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: |
-            # run 0 tests as queue is consumed ||
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=false
-            bundle exec rake knapsack_pro:queue:rspec
-      - run:
-          working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
-          command: |
-            # retry the same split ||
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
+            # run 0 tests because nothing failed in the previous step ||
+            export KNAPSACK_PRO_TEST_QUEUE_ID="<< pipeline.number >>:$CIRCLE_JOB--queue"
+            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--<< pipeline.number >>:$CIRCLE_JOB--queue"
             bundle exec rake knapsack_pro:queue:rspec
       - run:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: |
             # fallback ||
+            export KNAPSACK_PRO_TEST_QUEUE_ID="<< pipeline.number >>:$CIRCLE_JOB--queue--fallback"
+            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--<< pipeline.number >>:$CIRCLE_JOB--queue--fallback"
             export KNAPSACK_PRO_ENDPOINT=https://api-fake.knapsackpro.com
             export KNAPSACK_PRO_MAX_REQUEST_RETRIES=1
             bundle exec rake knapsack_pro:queue:rspec
@@ -266,8 +263,8 @@ jobs:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: |
             # split by test examples above the slow test file threshold ||
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--split-above-slow-test-file-threshold"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
+            export KNAPSACK_PRO_TEST_QUEUE_ID="<< pipeline.number >>:$CIRCLE_JOB--queue--split-above-slow-test-file-threshold"
+            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--<< pipeline.number >>:$CIRCLE_JOB--queue--split-above-slow-test-file-threshold"
             export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
             export KNAPSACK_PRO_SLOW_TEST_FILE_THRESHOLD=1
             bundle exec rake knapsack_pro:queue:rspec
@@ -275,8 +272,8 @@ jobs:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: |
             # split by test examples AND a single CI node ||
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--split--single-node--$CIRCLE_NODE_INDEX"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
+            export KNAPSACK_PRO_TEST_QUEUE_ID="<< pipeline.number >>:$CIRCLE_JOB--queue--split--single-node"
+            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--<< pipeline.number >>:$CIRCLE_JOB--queue--split--single-node"
             export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
             export KNAPSACK_PRO_CI_NODE_TOTAL=1
             export KNAPSACK_PRO_CI_NODE_INDEX=0
@@ -285,7 +282,8 @@ jobs:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: |
             # split custom files by test examples AND the --tag option passed ||
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--split-custom-files--tag-option"
+            export KNAPSACK_PRO_TEST_QUEUE_ID="<< pipeline.number >>:$CIRCLE_JOB--queue--split-custom-files--tag-option"
+            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--<< pipeline.number >>:$CIRCLE_JOB--queue--split-custom-files--tag-option"
             export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
             export KNAPSACK_PRO_SLOW_TEST_FILE_PATTERN="spec/bar_spec.rb"
             export SKIP_ME_OR_I_WILL_FAIL=true
@@ -296,8 +294,8 @@ jobs:
             # turnip ||
             mv .rspec .rspec.off
             cp .rspec.turnip .rspec
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--turnip"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
+            export KNAPSACK_PRO_TEST_QUEUE_ID="<< pipeline.number >>:$CIRCLE_JOB--queue--turnip"
+            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--<< pipeline.number >>:$CIRCLE_JOB--queue--turnip"
             export KNAPSACK_PRO_TEST_DIR=turnip
             export KNAPSACK_PRO_TEST_FILE_PATTERN="turnip/**/*.feature"
             export KNAPSACK_PRO_SLOW_TEST_FILE_PATTERN="turnip/acceptance/foo.feature"
@@ -312,8 +310,8 @@ jobs:
             # turnip retry ||
             mv .rspec .rspec.off
             cp .rspec.turnip .rspec
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--turnip"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
+            export KNAPSACK_PRO_TEST_QUEUE_ID="<< pipeline.number >>:$CIRCLE_JOB--queue--turnip"
+            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--<< pipeline.number >>:$CIRCLE_JOB--queue--turnip"
             export KNAPSACK_PRO_TEST_DIR=turnip
             export KNAPSACK_PRO_TEST_FILE_PATTERN="turnip/**/*.feature"
             export KNAPSACK_PRO_SLOW_TEST_FILE_PATTERN="turnip/acceptance/foo.feature"
@@ -326,7 +324,8 @@ jobs:
           working_directory: ~/knapsack_pro-ruby/rails-app-with-knapsack_pro
           command: |
             # separate queue initialization
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue-init"
+            export KNAPSACK_PRO_TEST_QUEUE_ID="<< pipeline.number >>:$CIRCLE_JOB--queue--init"
+            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--<< pipeline.number >>:$CIRCLE_JOB--queue--init"
             bundle exec rake knapsack_pro:queue:rspec:initialize
             bundle exec rake knapsack_pro:queue:rspec
 
@@ -434,19 +433,19 @@ workflows:
           matrix:
             parameters:
               ruby: ["3.3", "3.4", "4.0"]
-              rspec: ["3.12.3", "latest"]
+              rspec: ["3.12", "latest"]
       - e2e-regular-rspec:
-          name: e2e-regular__ruby-<< matrix.ruby >>__rspec-<< matrix.rspec >>
+          name: e2e-regular__ruby-<< matrix.ruby >>__rspec-<< matrix.rspec-rails >>
           matrix:
             parameters:
               ruby: ["3.3", "3.4", "4.0"]
-              rspec: ["3.12.3", "latest"]
+              rspec-rails: ["6.1.1", "latest"] # 6.1.1 uses rspec 3.12
       - e2e-queue-rspec:
-          name: e2e-queue__ruby-<< matrix.ruby >>__rspec-<< matrix.rspec >>
+          name: e2e-queue__ruby-<< matrix.ruby >>__rspec-<< matrix.rspec-rails >>
           matrix:
             parameters:
               ruby: ["3.3", "3.4", "4.0"]
-              rspec: ["3.12.3", "latest"]
+              rspec-rails: ["6.1.1", "latest"] # 6.1.1 uses rspec 3.12
       - e2e-regular-minitest:
           name: e2e-regular__ruby-<< matrix.ruby >>__minitest
           matrix:
