debug tests allocation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -244,49 +244,49 @@ jobs:
       - run:
           working_directory: ~/rails-app-with-knapsack_pro
           command: bin/rails db:setup
-      - run:
-          working_directory: ~/rails-app-with-knapsack_pro
-          command: |
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue"
-            bundle exec rake knapsack_pro:queue:rspec
-      - run:
-          working_directory: ~/rails-app-with-knapsack_pro
-          command: |
-            # run 0 tests as queue is consumed ||
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=false
-            bundle exec rake knapsack_pro:queue:rspec
-      - run:
-          working_directory: ~/rails-app-with-knapsack_pro
-          command: |
-            # retry the same split ||
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
-            bundle exec rake knapsack_pro:queue:rspec
-      - run:
-          working_directory: ~/rails-app-with-knapsack_pro
-          command: |
-            # fallback ||
-            export KNAPSACK_PRO_ENDPOINT=https://api-fake.knapsackpro.com
-            export KNAPSACK_PRO_MAX_REQUEST_RETRIES=1
-            bundle exec rake knapsack_pro:queue:rspec
-      - run:
-          working_directory: ~/rails-app-with-knapsack_pro
-          command: |
-            # split by test examples ||
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--split"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
-            export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
-            bundle exec rake knapsack_pro:queue:rspec
-      - run:
-          working_directory: ~/rails-app-with-knapsack_pro
-          command: |
-            # split by test examples above the slow test file threshold ||
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--split-above-slow-test-file-threshold"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
-            export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
-            export KNAPSACK_PRO_SLOW_TEST_FILE_THRESHOLD=1
-            bundle exec rake knapsack_pro:queue:rspec
+      #- run:
+          #working_directory: ~/rails-app-with-knapsack_pro
+          #command: |
+            #export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue"
+            #bundle exec rake knapsack_pro:queue:rspec
+      #- run:
+          #working_directory: ~/rails-app-with-knapsack_pro
+          #command: |
+            ## run 0 tests as queue is consumed ||
+            #export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue"
+            #export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=false
+            #bundle exec rake knapsack_pro:queue:rspec
+      #- run:
+          #working_directory: ~/rails-app-with-knapsack_pro
+          #command: |
+            ## retry the same split ||
+            #export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue"
+            #export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
+            #bundle exec rake knapsack_pro:queue:rspec
+      #- run:
+          #working_directory: ~/rails-app-with-knapsack_pro
+          #command: |
+            ## fallback ||
+            #export KNAPSACK_PRO_ENDPOINT=https://api-fake.knapsackpro.com
+            #export KNAPSACK_PRO_MAX_REQUEST_RETRIES=1
+            #bundle exec rake knapsack_pro:queue:rspec
+      #- run:
+          #working_directory: ~/rails-app-with-knapsack_pro
+          #command: |
+            ## split by test examples ||
+            #export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--split"
+            #export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
+            #export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
+            #bundle exec rake knapsack_pro:queue:rspec
+      #- run:
+          #working_directory: ~/rails-app-with-knapsack_pro
+          #command: |
+            ## split by test examples above the slow test file threshold ||
+            #export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--split-above-slow-test-file-threshold"
+            #export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
+            #export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
+            #export KNAPSACK_PRO_SLOW_TEST_FILE_THRESHOLD=1
+            #bundle exec rake knapsack_pro:queue:rspec
       - run:
           working_directory: ~/rails-app-with-knapsack_pro
           command: |
@@ -294,50 +294,51 @@ jobs:
             export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--split--single-node"
             export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
             export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
+            export KNAPSACK_PRO_LOG_LEVEL=debug
             export KNAPSACK_PRO_CI_NODE_TOTAL=1
             export KNAPSACK_PRO_CI_NODE_INDEX=0
             bundle exec rake knapsack_pro:queue:rspec
-      - run:
-          working_directory: ~/rails-app-with-knapsack_pro
-          command: |
-            # split custom files by test examples AND the --tag option passed ||
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--split-custom-files--tag-option"
-            export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
-            export KNAPSACK_PRO_SLOW_TEST_FILE_PATTERN="spec/bar_spec.rb"
-            export SKIP_ME_OR_I_WILL_FAIL=true
-            bundle exec rake "knapsack_pro:queue:rspec[--tag tag_x -t ~tag_y --tag ~skip_me_or_i_will_fail --format documentation]"
-      - run:
-          working_directory: ~/rails-app-with-knapsack_pro
-          command: |
-            # turnip ||
-            mv .rspec .rspec.off
-            cp .rspec.turnip .rspec
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--turnip"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
-            export KNAPSACK_PRO_TEST_DIR=turnip
-            export KNAPSACK_PRO_TEST_FILE_PATTERN="turnip/**/*.feature"
-            export KNAPSACK_PRO_SLOW_TEST_FILE_PATTERN="turnip/acceptance/foo.feature"
-            bundle exec rake knapsack_pro:queue:rspec
-            RSPEC_EXIT_CODE=$?
-            rm .rspec
-            mv .rspec.off .rspec
-            exit $RSPEC_EXIT_CODE
-      - run:
-          working_directory: ~/rails-app-with-knapsack_pro
-          command: |
-            # turnip retry ||
-            mv .rspec .rspec.off
-            cp .rspec.turnip .rspec
-            export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--turnip"
-            export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
-            export KNAPSACK_PRO_TEST_DIR=turnip
-            export KNAPSACK_PRO_TEST_FILE_PATTERN="turnip/**/*.feature"
-            export KNAPSACK_PRO_SLOW_TEST_FILE_PATTERN="turnip/acceptance/foo.feature"
-            bundle exec rake knapsack_pro:queue:rspec
-            RSPEC_EXIT_CODE=$?
-            rm .rspec
-            mv .rspec.off .rspec
-            exit $RSPEC_EXIT_CODE
+      #- run:
+          #working_directory: ~/rails-app-with-knapsack_pro
+          #command: |
+            ## split custom files by test examples AND the --tag option passed ||
+            #export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--split-custom-files--tag-option"
+            #export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
+            #export KNAPSACK_PRO_SLOW_TEST_FILE_PATTERN="spec/bar_spec.rb"
+            #export SKIP_ME_OR_I_WILL_FAIL=true
+            #bundle exec rake "knapsack_pro:queue:rspec[--tag tag_x -t ~tag_y --tag ~skip_me_or_i_will_fail --format documentation]"
+      #- run:
+          #working_directory: ~/rails-app-with-knapsack_pro
+          #command: |
+            ## turnip ||
+            #mv .rspec .rspec.off
+            #cp .rspec.turnip .rspec
+            #export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--turnip"
+            #export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
+            #export KNAPSACK_PRO_TEST_DIR=turnip
+            #export KNAPSACK_PRO_TEST_FILE_PATTERN="turnip/**/*.feature"
+            #export KNAPSACK_PRO_SLOW_TEST_FILE_PATTERN="turnip/acceptance/foo.feature"
+            #bundle exec rake knapsack_pro:queue:rspec
+            #RSPEC_EXIT_CODE=$?
+            #rm .rspec
+            #mv .rspec.off .rspec
+            #exit $RSPEC_EXIT_CODE
+      #- run:
+          #working_directory: ~/rails-app-with-knapsack_pro
+          #command: |
+            ## turnip retry ||
+            #mv .rspec .rspec.off
+            #cp .rspec.turnip .rspec
+            #export KNAPSACK_PRO_BRANCH="$CIRCLE_BRANCH--$CIRCLE_BUILD_NUM--queue--turnip"
+            #export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
+            #export KNAPSACK_PRO_TEST_DIR=turnip
+            #export KNAPSACK_PRO_TEST_FILE_PATTERN="turnip/**/*.feature"
+            #export KNAPSACK_PRO_SLOW_TEST_FILE_PATTERN="turnip/acceptance/foo.feature"
+            #bundle exec rake knapsack_pro:queue:rspec
+            #RSPEC_EXIT_CODE=$?
+            #rm .rspec
+            #mv .rspec.off .rspec
+            #exit $RSPEC_EXIT_CODE
 
   e2e-regular-minitest:
     parallelism: 2
